version: '3.9'  # Указывает версию формата Compose-файла. 3.9 — актуальная версия для Docker Compose V2.

services:  # Определение всех сервисов (контейнеров), которые будут запущены.

  app:  # Сервис Flask-приложения.
    build: .  # Собирает образ из Dockerfile в текущей директории.
    container_name: flask_app  # Устанавливает читаемое имя контейнера.
    restart: always  # Автоматический перезапуск контейнера при сбое или перезагрузке.
    environment:  # Переменные окружения, передаваемые внутрь контейнера.
      DB_HOST: db  # Имя хоста базы данных (имя другого сервиса в Compose).
      DB_PORT: 5432  # Порт PostgreSQL (по умолчанию).
      DB_NAME: flaskdb  # Имя базы данных, к которой подключается приложение.
      DB_USER: user  # Имя пользователя базы данных.
      DB_PASSWORD: password  # Пароль пользователя.
    depends_on:  # Указывает, что сначала должен быть запущен контейнер 'db'.
      - db
    networks:
      - backend  # Присоединяет контейнер к внутренней сети backend.

  db:  # Сервис базы данных PostgreSQL.
    image: postgres:14  # Использует официальный образ PostgreSQL версии 14.
    container_name: postgres_db  # Читаемое имя контейнера базы данных.
    restart: always  # Автоматический перезапуск при сбоях.
    environment:  # Переменные для инициализации базы данных.
      POSTGRES_DB: flaskdb  # Имя создаваемой базы данных.
      POSTGRES_USER: user  # Имя создаваемого пользователя.
      POSTGRES_PASSWORD: password  # Пароль пользователя.
    volumes:
      - db_data:/var/lib/postgresql/data  # Монтирует том для хранения данных БД (персистентность).
    networks:
      - backend  # Подключение к внутренней сети backend.

  nginx:  # Сервис веб-сервера NGINX, действующего как реверс-прокси.
    image: nginx:latest  # Последний официальный образ NGINX.
    container_name: nginx  # Явное имя контейнера.
    restart: always  # Перезапуск при сбоях или перезагрузке.
    ports:
      - "443:443"  # Проброс порта 443 с хоста в контейнер (для HTTPS).
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Монтирует локальный конфиг nginx.
      - ./certs:/etc/ssl/certs:ro  # Монтирует папку с SSL-сертификатами (только чтение).
    depends_on:
      - app  # Запускается после сервиса app, чтобы проксировать его.
    networks:
      - backend  # Доступ к внутренним сервисам.
      - frontend  # Доступ к внешней сети (интернету).

volumes:  # Объявление именованных томов.
  db_data:  # Том для хранения данных PostgreSQL вне контейнера.

networks:  # Объявление сетей Docker.
  backend:  # Внутренняя сеть между сервисами (app, db, nginx).
  frontend:  # Внешняя сеть, через которую nginx доступен снаружи.

